### ISSUE TITLE
Requiring as a sub package (non-root)

### ISSUE THREAD

**Issue by markroland** [didaxRedux/php-ezPDF#2]
I'm trying to make this a dependency of another package, which is listed in my root composer.json.

I'm running into problems because this package does not have a stable release on Packagist. Would it be possible to add one, such as "v0.12.0" or "v0.12.1"?

Thank you.

**Comment by didaxRedux** [comment]
I've changed the version inside composer.json
Is it right? I have to do some other operation?

**Comment by markroland** [comment]
Thanks for the response!

I believe you actually need to "tag" the release in git/github

**Comment by didaxRedux** [comment]
Thank you :)
Hope I've done the right steps...

**Comment by markroland** [comment]
I believe this was just what I needed. Thank you so much!
